name: Build and release LaTeX PDF

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6

      - name: LaTeX Compile
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: .
          root_file: reti-di-calcolatori.tex

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: Latest version # Release name
          files: reti-di-calcolatori.pdf # Output PDF name
          body: "Automatically compiled from commit ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
